/*
 * Video Doorbell for LG webOS
 * Displays sequential JPEG snapshots generated by Home Assistant.
 * Unique filenames avoid aggressive image caching on older webOS browsers.
 */
window.onload = function () {
    const box = document.getElementById("box");
    const img = document.createElement("img");
    let frameNumber = 1;
    let loading = false;
    let stopped = false;

    img.style.width = "100%";
    img.style.height = "100%";
    img.style.objectFit = "cover";
    img.style.display = "block";
    box.innerHTML = "";
    box.appendChild(img);

    // Convert 1 to frame0001.jpg, 12 to frame0012.jpg, and so on.
    function getFrameName(number) {
        return "frame" + String(number).padStart(4, "0") + ".jpg";
    }

    function refreshSnapshot() {
        // Prevent overlapping requests and stop after closing.
        if (loading || stopped) return;
        if (frameNumber > CONFIG.MAX_FRAMES) return;

        loading = true;
        const currentNumber = frameNumber;
        const filename = getFrameName(currentNumber);
        const url = CONFIG.BASE_URL + filename + "?cache=" + Date.now();
        const preload = new Image();

        preload.onload = function () {
            if (!stopped) {
                img.src = preload.src;
                frameNumber = currentNumber + 1;
            }
            loading = false;
        };

        preload.onerror = function () {
            // The frame may not exist yet. Retry it during the next interval.
            loading = false;
            console.log("Snapshot not available yet: " + filename);
        };

        preload.src = url;
    }

    refreshSnapshot();
    const refreshInterval = setInterval(refreshSnapshot, CONFIG.REFRESH_INTERVAL);

    // Close the overlay automatically after the configured display time.
    setTimeout(function () {
        stopped = true;
        clearInterval(refreshInterval);
        setTimeout(function () {
            if (window.webOSSystem) window.webOSSystem.close();
            else window.close();
        }, 300);
    }, CONFIG.DISPLAY_TIME);
};
